server:
  port: 8080
#  servlet:
#    context-path: /security-springboot
spring:
  application:
    name: security-springboot
  datasource:
    url: jdbc:mysql://localhost:3306/ditu?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/ditu